# -*- coding: utf-8 -*-
# Custom fields converted from the alshumul production system.
# Data is embedded (static) so the app is independent of any export folder.

CUSTOM_FIELDS = [
    {'dt': 'AML Circulars', 'label': 'Workflow State', 'fieldname': 'workflow_state', 'fieldtype': 'Link', 'precision': '', 'options': 'Workflow State', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 1, 'print_hide': 0, 'no_copy': 1, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Company', 'fieldname': 'column_break_10', 'insert_after': 'default_employee_advance_account', 'fieldtype': 'Column Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Company', 'label': 'HR & Payroll', 'fieldname': 'hr_and_payroll_tab', 'insert_after': 'credit_limit', 'fieldtype': 'Tab Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Company', 'label': 'HR & Payroll Settings', 'fieldname': 'hr_settings_section', 'insert_after': 'hr_and_payroll_tab', 'fieldtype': 'Section Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Department', 'label': 'Approvers', 'fieldname': 'approvers', 'insert_after': 'leave_block_list', 'fieldtype': 'Section Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0, 'description': 'The first Approver in the list will be set as the default Approver.'},
    {'dt': 'Department', 'fieldname': 'column_break_9', 'insert_after': 'payroll_cost_center', 'fieldtype': 'Column Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Department', 'label': 'Expense Approver', 'fieldname': 'expense_approvers', 'insert_after': 'leave_approvers', 'fieldtype': 'Table', 'precision': '', 'options': 'Department Approver', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Department', 'label': 'Leave Approver', 'fieldname': 'leave_approvers', 'insert_after': 'shift_request_approver', 'fieldtype': 'Table', 'precision': '', 'options': 'Department Approver', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Department', 'fieldname': 'section_break_4', 'insert_after': 'disabled', 'fieldtype': 'Section Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Department', 'label': 'Shift Request Approver', 'fieldname': 'shift_request_approver', 'insert_after': 'approvers', 'fieldtype': 'Table', 'precision': '', 'options': 'Department Approver', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Designation', 'label': 'Required Skills', 'fieldname': 'required_skills_section', 'insert_after': 'appraisal_template', 'fieldtype': 'Section Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Designation', 'label': 'Skills', 'fieldname': 'skills', 'insert_after': 'required_skills_section', 'fieldtype': 'Table', 'precision': '', 'options': 'Designation Skill', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Employee Onboarding', 'label': '💨 البصمات', 'fieldname': 'custom_البصمات', 'insert_after': 'employee', 'fieldtype': 'Data', 'precision': '', 'options': 'يسب\nسيب\nسيب\nسيب', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Employee', 'label': 'Approvers', 'fieldname': 'approvers_section', 'insert_after': 'default_shift', 'fieldtype': 'Section Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Employee', 'fieldname': 'column_break_45', 'insert_after': 'leave_approver', 'fieldtype': 'Column Break', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Employee', 'label': 'Health Insurance No', 'fieldname': 'health_insurance_no', 'insert_after': 'health_insurance_provider', 'fieldtype': 'Data', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Employee', 'label': 'Health Insurance Provider', 'fieldname': 'health_insurance_provider', 'insert_after': 'health_insurance_section', 'fieldtype': 'Link', 'precision': '', 'options': 'Employee Health Insurance', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Employee', 'label': 'Health Insurance', 'fieldname': 'health_insurance_section', 'insert_after': 'health_details', 'fieldtype': 'Section Break', 'precision': '', 'collapsible': 1, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Employee', 'label': 'Shift Request Approver', 'fieldname': 'shift_request_approver', 'insert_after': 'column_break_45', 'fieldtype': 'Link', 'precision': '', 'options': 'User', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Project', 'label': 'Total Expense Claim (via Expense Claims)', 'fieldname': 'total_expense_claim', 'insert_after': 'total_costing_amount', 'fieldtype': 'Currency', 'precision': '', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 1, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Short Leave', 'label': 'Workflow State', 'fieldname': 'workflow_state', 'fieldtype': 'Link', 'precision': '', 'options': 'Workflow State', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 0, 'hidden': 1, 'print_hide': 0, 'no_copy': 1, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Task', 'label': 'Total Expense Claim (via Expense Claim)', 'fieldname': 'total_expense_claim', 'insert_after': 'total_costing_amount', 'fieldtype': 'Currency', 'precision': '', 'options': 'Company:company:default_currency', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 1, 'hidden': 0, 'print_hide': 0, 'no_copy': 0, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
    {'dt': 'Timesheet', 'label': 'Salary Slip', 'fieldname': 'salary_slip', 'insert_after': 'column_break_3', 'fieldtype': 'Link', 'precision': '', 'options': 'Salary Slip', 'collapsible': 0, 'reqd': 0, 'unique': 0, 'read_only': 1, 'hidden': 0, 'print_hide': 1, 'no_copy': 1, 'in_list_view': 0, 'in_standard_filter': 0, 'in_global_search': 0, 'bold': 0, 'search_index': 0, 'translatable': 0},
]
